### PR TITLE
gstreamer 1.24.0 -> 1.24.7

### PR DESCRIPTION
**Pull request by Zopolis4**
## Description
yeah idk where ur getting these minimum glibc values from, but thats another one down.

##
Builds:
- [x] `x86_64`
- [ ] `i686`
- [x] `armv7l`
##
Tested & Working properly:
- [x] `x86_64`
- [ ] `i686`
- [x] `armv7l` 
##
### Run the following to get this pull request's changes locally for testing.
```bash
CREW_REPO=https://github.com/Zopolis4/chromebrew.git CREW_BRANCH=2really crew update \
&& yes | crew upgrade
```

### CODE REVIEW

**Review by uberhacker — APPROVED** [review]

**Comment by satmandu** [comment]
Pulseaudio also needs an update?

**Comment by Zopolis4** [comment]
Working on it, takes a while to build and i needed gstreamer first because of the circular dependencies.

**Comment by Zopolis4** [comment]
Oh-- you mean in this PR itself so that unit tests pass. hm

**Review by satmandu — APPROVED** [review]

**Comment by Zopolis4** [comment]
not ready yet, still need arm rebuild

**Comment by Zopolis4** [comment]
good to go

**Review by satmandu — APPROVED** [review]

**Pull request merged**
