### PR TITLE
Yt_dlp 2023.09.24 => 2023.11.16

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on all architectures.

### CODE REVIEW

**Review by satmandu — CHANGES_REQUESTED** [review]
This appears to include a bunch of dependencies looking at the file lists... Should those be broken out into separate dependencies?

**Comment by uberhacker** [comment]
> This appears to include a bunch of dependencies looking at the file lists... Should those be broken out into separate dependencies?

It's a rabbit hole.  The dependencies likely change every time the yt_dlp package is updated.  I just update everything as I go because the manifest files change.

**Comment by satmandu** [comment]
Can you just update py3_certifi and the other one and add them as deps so we don't accidentally overwrite them if they get installed separately?

**Comment by uberhacker** [comment]
> Can you just update py3_certifi and py3_websockets and add them as deps so we don't accidentally overwrite them if they get installed separately?



> Can you just update py3_certifi and py3_websockets and add them as deps so we don't accidentally overwrite them if they get installed separately?

That's fair.

**Review by satmandu — APPROVED** [review]

**Pull request merged**
