### PR TITLE
lib/color: Refactor `color.rb`, add more colors

### PR DESCRIPTION
**Pull request by supechicken**
### New changes
- Fix color detection on interactive terminals
- All color codes are listed on one hash table instead of each separated function
- Add new colors: lighter version of `black-lightgray` but without bold, can be used with:
```shell
# existing `lightgreen` function (with bold words)
puts "hello".lightgreen # => same as current

# existing `lightgreen` function with :no_bold option specified (without bold words)
puts "hello".lightgreen(:no_bold) # => identical color with the bold varient but without bold
```

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/supechicken/chromebrew.git CREW_TESTING_BRANCH=new_color CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by uberhacker** [comment]
Rubocop frisking results:
```
lib/color.rb:7:9: C: [Correctable] Layout/FirstHashElementIndentation: Use 2 spaces for indentation in a hash, relative to the start of the line where the left curly brace is.
        black: 30,
        ^^^^^^^^^
lib/color.rb:16:5: C: [Correctable] Layout/CommentIndentation: Incorrect indentation detected (column 4 instead of 11).
    # colors with bold varient available
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/color.rb:61:4: C: [Correctable] Layout/TrailingEmptyLines: Final newline missing.
```

**Comment by satmandu** [comment]
@supechicken note that the PR lists whether the rubocop run succeeded or not.

**Review by uberhacker — COMMENTED** [review]
Do we need to update crew with the new color references from color.rb?

**Comment by supechicken** [comment]
> Do we need to update crew with the new color references from color.rb?

No, all functions are "backward-compatible"😉

**Pull request merged**
