### PR TITLE
python2: Cleanup, use `clang` for faster build

### PR DESCRIPTION
**Pull request by supechicken**
### Changes
- Fix some tests by changing the `TMPDIR` environment variable
- Use `clang` for faster building time
- Cleanup

Binaries rebuild required

Build successfully on `x86_64`

### CODE REVIEW

**Comment by satmandu** [comment]
Should we wait on this until we have a build of LLVM 14? If we're updating this for speed, makes sense to use the most recent clang too?

(LLVM update pending finding a good way to generate separate lib and binary packages from a single lvm2 package file to avoid building multiple times.)

**Comment by supechicken** [comment]
> Should we wait on this until we have a build of LLVM 14? If we're updating this for speed, makes sense to use the most recent clang too?
> 
> (LLVM update pending finding a good way to generate separate lib and binary packages from a single lvm2 package file to avoid building multiple times.)

Maybe wait for the next `armv7l` release of `mold` also?

**Comment by satmandu** [comment]
Doesn't build on i686 with a compiler error...

**Comment by satmandu** [comment]
```
Building from source, this may take a while...
configure: WARNING: unrecognized options: --with-loadable-sqlite-extensions
checking build system type... i686-cros-linux-gnu
checking host system type... i686-cros-linux-gnu
checking for python2.7... python2.7
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... linux2
checking EXTRAPLATDIR...
checking for --without-gcc... no
checking for --with-icc... no
checking for i686-cros-linux-gnu-gcc... clang -Wno-unused-command-line-argument -Wno-ignored-optimization-argument
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/python2.20220509151516.dir/Python-2.7.18':
configure: error: C compiler cannot create executables
See `config.log' for more details
python2 failed to build: `CFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " CXXFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " FCFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " FFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " LDFLAGS="-flto " TMPDIR="/usr/local/tmp" CC="clang -Wno-unused-command-line-argument -Wno-ignored-optimization-argument" CXX="clang++ -Wno-unused-command-line-argument -Wno-ignored-optimization-argument" AR="llvm-ar" NM="llvm-nm" RANLIB="llvm-ranlib" bash -c ./configure --prefix=/usr/local --libdir=/usr/local/lib --mandir=/usr/local/share/man --build=i686-cros-linux-gnu --host=i686-cros-linux-gnu --target=i686-cros-linux-gnu --program-prefix='' --program-suffix=''   --with-fpectl   --enable-ipv6   --with-threads   --enable-unicode=ucs4   --with-computed-gotos   --with-loadable-sqlite-extensions   --without-ensurepip   --enable-optimizations   --with-lto   --with-system-ffi   --with-system-expat   --enable-shared
` exited with 77
```

```
configure:3968: checking whether the C compiler works
configure:3990: clang -Wno-unused-command-line-argument -Wno-ignored-optimization-argument -O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold   -flto  conftest.c  >&5
mold: error: undefined symbol: /usr/local/lib/crti.o: __x86.get_pc_thunk.bx
mold: error: undefined symbol: /usr/local/lib/crti.o: __x86.get_pc_thunk.bx
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3994: $? = 1
configure:4032: result: no
configure: failed program was:
| /* confdefs.h */
| #define _GNU_SOURCE 1
| #define _NETBSD_SOURCE 1
| #define __BSD_VISIBLE 1
| #define _BSD_TYPES 1
| #define _DARWIN_C_SOURCE 1
| #define _XOPEN_SOURCE 600
| #define _XOPEN_SOURCE_EXTENDED 1
| #define _POSIX_C_SOURCE 200112L
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:4037: error: in `/usr/local/tmp/crew/python2.20220509151516.dir/Python-2.7.18':
configure:4039: error: C compiler cannot create executables
See `config.log' for more details
```

(This is a [mold issue](https://github.com/rui314/mold/issues/483).)

Using `CREW_LINKER=gold` gets us past this error on i686.

**Comment by satmandu** [comment]
Using `CREW_LINKER=lld` I get this: 

```
clang -Wno-unused-command-line-argument -Wno-ignored-optimization-argument -pthread -c -fPIC -fno-strict-aliasing -OPT:Olimit=0 -O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=lld  -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -fprofile-instr-generate -flto -g -I. -IInclude -I./Include  -fPIC -DPy_BUILD_CORE -o Modules/_math.o Modules/_math.c
/usr/local/bin/install -c -m 644 ./Tools/gdb/libpython.py python-gdb.py
clang -Wno-unused-command-line-argument -Wno-ignored-optimization-argument -pthread -c -fno-strict-aliasing -OPT:Olimit=0 -O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=lld  -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -fprofile-instr-generate -flto -g -I. -IInclude -I./Include  -fPIC -DPy_BUILD_CORE \
      -DGITVERSION="\"`LC_ALL=C `\"" \
      -DGITTAG="\"`LC_ALL=C `\"" \
      -DGITBRANCH="\"`LC_ALL=C `\"" \
      -o Modules/getbuildinfo.o ./Modules/getbuildinfo.c
rm -f libpython2.7.a
if test libpython2.7.so.1.0 != libpython2.7.so; then \
        clang -Wno-unused-command-line-argument -Wno-ignored-optimization-argument -pthread -shared -flto  -fprofile-instr-generate -flto -g -Wl,-hlibpython2.7.so.1.0 -o libpython2.7.so.1.0 Modules/getbuildinfo.o Parser/acceler.o Parser/grammar1.o Parser/listnode.o Parser/node.o Parser/parser.o Parser/parsetok.o Parser/bitset.o Parser/metagrammar.o Parser/firstsets.o Parser/grammar.o Parser/pgen.o Parser/myreadline.o Parser/tokenizer.o Objects/abstract.o Objects/boolobject.o Objects/bufferobject.o Objects/bytes_methods.o Objects/bytearrayobject.o Objects/capsule.o Objects/cellobject.o Objects/classobject.o Objects/cobject.o Objects/codeobject.o Objects/complexobject.o Objects/descrobject.o Objects/enumobject.o Objects/exceptions.o Objects/genobject.o Objects/fileobject.o Objects/floatobject.o Objects/frameobject.o Objects/funcobject.o Objects/intobject.o Objects/iterobject.o Objects/listobject.o Objects/longobject.o Objects/dictobject.o Objects/memoryobject.o Objects/methodobject.o Objects/moduleobject.o Objects/object.o Objects/obmalloc.o Objects/rangeobject.o Objects/setobject.o Objects/sliceobject.o Objects/stringobject.o Objects/structseq.o Objects/tupleobject.o Objects/typeobject.o Objects/weakrefobject.o Objects/unicodeobject.o Objects/unicodectype.o Python/_warnings.o Python/Python-ast.o Python/asdl.o Python/ast.o Python/bltinmodule.o Python/ceval.o Python/compile.o Python/codecs.o Python/errors.o Python/frozen.o Python/frozenmain.o Python/future.o Python/getargs.o Python/getcompiler.o Python/getcopyright.o Python/getplatform.o Python/getversion.o Python/graminit.o Python/import.o Python/importdl.o Python/marshal.o Python/modsupport.o Python/mystrtoul.o Python/mysnprintf.o Python/peephole.o Python/pyarena.o Python/pyctype.o Python/pyfpe.o Python/pymath.o Python/pystate.o Python/pythonrun.o Python/random.o Python/structmember.o Python/symtable.o Python/sysmodule.o Python/traceback.o Python/getopt.o Python/pystrcmp.o Python/pystrtod.o Python/dtoa.o Python/formatter_unicode.o Python/formatter_string.o Python/dynload_shlib.o   Python/thread.o Modules/config.o Modules/getpath.o Modules/main.o Modules/gcmodule.o  Modules/threadmodule.o  Modules/signalmodule.o  Modules/posixmodule.o  Modules/errnomodule.o  Modules/pwdmodule.o  Modules/_sre.o  Modules/_codecsmodule.o  Modules/_weakref.o  Modules/zipimport.o  Modules/symtablemodule.o  Modules/xxsubtype.o   -lpthread -ldl  -lutil  -lm ; \
        ln -f libpython2.7.so.1.0 libpython2.7.so; \
else \  
        clang -Wno-unused-command-line-argument -Wno-ignored-optimization-argument -pthread -shared -flto  -fprofile-instr-generate -flto -g -o libpython2.7.so Modules/getbuildinfo.o Parser/acceler.o Parser/grammar1.o Parser/listnode.o Parser/node.o Parser/parser.o Parser/parsetok.o Parser/bitset.o Parser/metagrammar.o Parser/firstsets.o Parser/grammar.o Parser/pgen.o Parser/myreadline.o Parser/tokenizer.o Objects/abstract.o Objects/boolobject.o Objects/bufferobject.o Objects/bytes_methods.o Objects/bytearrayobject.o Objects/capsule.o Objects/cellobject.o Objects/classobject.o Objects/cobject.o Objects/codeobject.o Objects/complexobject.o Objects/descrobject.o Objects/enumobject.o Objects/exceptions.o Objects/genobject.o Objects/fileobject.o Objects/floatobject.o Objects/frameobject.o Objects/funcobject.o Objects/intobject.o Objects/iterobject.o Objects/listobject.o Objects/longobject.o Objects/dictobject.o Objects/memoryobject.o Objects/methodobject.o Objects/moduleobject.o Objects/object.o Objects/obmalloc.o Objects/rangeobject.o Objects/setobject.o Objects/sliceobject.o Objects/stringobject.o Objects/structseq.o Objects/tupleobject.o Objects/typeobject.o Objects/weakrefobject.o Objects/unicodeobject.o Objects/unicodectype.o Python/_warnings.o Python/Python-ast.o Python/asdl.o Python/ast.o Python/bltinmodule.o Python/ceval.o Python/compile.o Python/codecs.o Python/errors.o Python/frozen.o Python/frozenmain.o Python/future.o Python/getargs.o Python/getcompiler.o Python/getcopyright.o Python/getplatform.o Python/getversion.o Python/graminit.o Python/import.o Python/importdl.o Python/marshal.o Python/modsupport.o Python/mystrtoul.o Python/mysnprintf.o Python/peephole.o Python/pyarena.o Python/pyctype.o Python/pyfpe.o Python/pymath.o Python/pystate.o Python/pythonrun.o Python/random.o Python/structmember.o Python/symtable.o Python/sysmodule.o Python/traceback.o Python/getopt.o Python/pystrcmp.o Python/pystrtod.o Python/dtoa.o Python/formatter_unicode.o Python/formatter_string.o Python/dynload_shlib.o   Python/thread.o Modules/config.o Modules/getpath.o Modules/main.o Modules/gcmodule.o  Modules/threadmodule.o  Modules/signalmodule.o  Modules/posixmodule.o  Modules/errnomodule.o  Modules/pwdmodule.o  Modules/_sre.o  Modules/_codecsmodule.o  Modules/_weakref.o  Modules/zipimport.o  Modules/symtablemodule.o  Modules/xxsubtype.o   -lpthread -ldl  -lutil  -lm ; \
fi
llvm-ar rc libpython2.7.a Modules/getbuildinfo.o
llvm-ar rc libpython2.7.a Parser/acceler.o Parser/grammar1.o Parser/listnode.o Parser/node.o Parser/parser.o Parser/parsetok.o Parser/bitset.o Parser/metagrammar.o Parser/firstsets.o Parser/grammar.o Parser/pgen.o Parser/myreadline.o Parser/tokenizer.o
llvm-ar rc libpython2.7.a Objects/abstract.o Objects/boolobject.o Objects/bufferobject.o Objects/bytes_methods.o Objects/bytearrayobject.o Objects/capsule.o Objects/cellobject.o Objects/classobject.o Objects/cobject.o Objects/codeobject.o Objects/complexobject.o Objects/descrobject.o Objects/enumobject.o Objects/exceptions.o Objects/genobject.o Objects/fileobject.o Objects/floatobject.o Objects/frameobject.o Objects/funcobject.o Objects/intobject.o Objects/iterobject.o Objects/listobject.o Objects/longobject.o Objects/dictobject.o Objects/memoryobject.o Objects/methodobject.o Objects/moduleobject.o Objects/object.o Objects/obmalloc.o Objects/rangeobject.o Objects/setobject.o Objects/sliceobject.o Objects/stringobject.o Objects/structseq.o Objects/tupleobject.o Objects/typeobject.o Objects/weakrefobject.o Objects/unicodeobject.o Objects/unicodectype.o
llvm-ar rc libpython2.7.a Python/_warnings.o Python/Python-ast.o Python/asdl.o Python/ast.o Python/bltinmodule.o Python/ceval.o Python/compile.o Python/codecs.o Python/errors.o Python/frozen.o Python/frozenmain.o Python/future.o Python/getargs.o Python/getcompiler.o Python/getcopyright.o Python/getplatform.o Python/getversion.o Python/graminit.o Python/import.o Python/importdl.o Python/marshal.o Python/modsupport.o Python/mystrtoul.o Python/mysnprintf.o Python/peephole.o Python/pyarena.o Python/pyctype.o Python/pyfpe.o Python/pymath.o Python/pystate.o Python/pythonrun.o Python/random.o Python/structmember.o Python/symtable.o Python/sysmodule.o Python/traceback.o Python/getopt.o Python/pystrcmp.o Python/pystrtod.o Python/dtoa.o Python/formatter_unicode.o Python/formatter_string.o Python/dynload_shlib.o   Python/thread.o
llvm-ar rc libpython2.7.a Modules/config.o Modules/getpath.o Modules/main.o Modules/gcmodule.o
llvm-ar rc libpython2.7.a Modules/threadmodule.o  Modules/signalmodule.o  Modules/posixmodule.o  Modules/errnomodule.o  Modules/pwdmodule.o  Modules/_sre.o  Modules/_codecsmodule.o  Modules/_weakref.o  Modules/zipimport.o  Modules/symtablemodule.o  Modules/xxsubtype.o
llvm-ranlib libpython2.7.a
clang-14: error: unable to execute command: Segmentation fault (core dumped)
clang-14: error: linker command failed due to signal (use -v to see invocation)
ln: failed to access 'libpython2.7.so.1.0': No such file or directory
make[2]: *** [Makefile:560: libpython2.7.so] Error 1
make[2]: Leaving directory '/usr/local/tmp/crew/python2.20220509152603.dir/Python-2.7.18'
make[1]: *** [Makefile:453: build_all_generate_profile] Error 2
make[1]: Leaving directory '/usr/local/tmp/crew/python2.20220509152603.dir/Python-2.7.18'
make: *** [Makefile:438: profile-opt] Error 2
```

**Pull request closed without merging**
