### PR TITLE
Update fmt to 8.1.1

### PR DESCRIPTION
**Pull request by Zopolis4**
## Description
Update libfmt to 8.1.1.

## Works properly:
Had package conflict errors in the chroot despite not having libfmt installed, they persisted through a couple of builds so I don't know if this is an actual problem with the package or just my enviro.
- [ ] `x86_64`
- [ ] `i686`
- [ ] `armv7l`

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/Zopolis4/chromebrew.git CREW_TESTING_BRANCH=fmt8 CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by satmandu** [comment]
Building this now...

**Comment by satmandu** [comment]
Failures on `armv7l` due to this error:
```
mold: error: /usr/local/tmp/ccAmdBsQ.ltrans1.ltrans.o:(.ARM.extab): R_ARM_PREL31 relocation at offset 0x1d4 against symbol `__gxx_personality_v0' can not be used; recompile with -fPIC
mold: error: /usr/local/tmp/ccAmdBsQ.ltrans1.ltrans.o:(.ARM.extab): R_ARM_PREL31 relocation at offset 0x1ec against symbol `__gxx_personality_v0' can not be used; recompile with -fPIC                        mold: error: /usr/local/tmp/ccAmdBsQ.ltrans1.ltrans.o:(.ARM.extab): R_ARM_PREL31 relocation at offset 0x20c against symbol `__gxx_personality_v0' can not be used; recompile with -fPIC
mold: error: /usr/local/tmp/ccAmdBsQ.ltrans1.ltrans.o:(.ARM.extab): R_ARM_PREL31 relocation at offset 0x294 against symbol `__gxx_personality_v0' can not be used; recompile with -fPIC
mold: error: /usr/local/tmp/ccAmdBsQ.ltrans1.ltrans.o:(.ARM.extab): R_ARM_PREL31 relocation at offset 0x2b8 against symbol `__gxx_personality_v0' can not be used; recompile with -fPIC                        mold: error: /usr/local/tmp/ccAmdBsQ.ltrans1.ltrans.o:(.ARM.extab): R_ARM_PREL31 relocation at offset 0x328 against symbol `__gxx_personality_v0' can not be used; recompile with -fPIC
collect2: error: ld returned 1 exit status                           make[2]: *** [CMakeFiles/fmt.dir/build.make:113: libfmt.so.8.1.1] Error 1
make[1]: *** [CMakeFiles/Makefile2:173: CMakeFiles/fmt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....                         [  7%] Linking CXX static library libgtest.a                         [  7%] Built target gtest
```

**Comment by satmandu** [comment]
Does fmt have a PIC configure option? Or do we need to specify that with CFLAGS?

**Comment by Zopolis4** [comment]
I don't see anything on the fmt repo, it seems like an upstream issue, would you mind reporting it?

**Comment by Zopolis4** [comment]
Following up on this, has it been reported/fixed?

**Comment by satmandu** [comment]
Good question. Let me try to build this again.

**Comment by satmandu** [comment]
Looks like the recent mold update fixed this build on armv7l.

**Review by satmandu — APPROVED** [review]

**Pull request merged**
