### PR TITLE
Fix installation on aarch64 devices

### LINKED ISSUE #8635: 🐞 Chromebrew install fails. (Chrome os 116)
**Describe the bug**

Chromebrew install fails with the error "Your device is not supported by Chromebrew yet, installing as armv7l." and then exits out to crosh
**To Reproduce**

1. I executed this command:

      ```shell
      chronos@juniper-rev4 / $ exec bash --init-file <(curl -Ls git.io/vddgY)

      ```

      Output:

Welcome to Chromebrew!
Please enter the developer mode password
Password: 
Your device is not supported by Chromebrew yet, installing as armv7l.

**Expected behavior**
Chromebrew installs correctly
**Screenshots**

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
bash: crew: command not found
***

**Additional context**
If my memory serves correctly, chromebrew installed correctly in ~2021 on the same chromebook

### PR DESCRIPTION
**Pull request by Zopolis4**
oops

Resolves #8635.

Unable to test because I don't have an aarch64 docker script, although I am confident this change will solve the issue.

### CODE REVIEW

**Comment by uberhacker** [comment]
Actually, what really makes sense is something like below:
```
if [[ "$USER_SPACE_ARCH" == 'aarch64' ]] && [[ "$ARCH" == 'aarch64' ]]; then
  echo_error "Your device is not supported by Chromebrew.  Binaries are not available yet."
  exit 1
fi
```

**Comment by Zopolis4** [comment]
As I understand it, we still do support aarch64 userspace, we just install armv7l binaries. @satmandu wrote the armv7l on aarch64 support, though, so they might know what the correct solution is.

**Comment by uberhacker** [comment]
> As I understand it, we still do support aarch64 userspace, we just install armv7l binaries. @satmandu wrote the armv7l on aarch64 support, though, so they might know what the correct solution is.

No, we only support armv7l userspace.  The architecture can still be aarch64, however.

**Comment by satmandu** [comment]
> > As I understand it, we still do support aarch64 userspace, we just install armv7l binaries. @satmandu wrote the armv7l on aarch64 support, though, so they might know what the correct solution is.
> 
> No, we only support armv7l userspace.  The architecture can still be aarch64, however.

We do experimentally support aarch64 userspace, since a stub armv7l userspace is also installed therein...

**Comment by uberhacker** [comment]
> > > As I understand it, we still do support aarch64 userspace, we just install armv7l binaries. @satmandu wrote the armv7l on aarch64 support, though, so they might know what the correct solution is.
> > 
> > 
> > No, we only support armv7l userspace.  The architecture can still be aarch64, however.
> 
> We do experimentally support aarch64 userspace, since a stub armv7l userspace is also installed therein...

No, if we supported aarch64 userspace then we would provide aarch64 binaries.  As soon as ChromeOS supports it then Chromebrew can support it.

**Comment by satmandu** [comment]
> > > > As I understand it, we still do support aarch64 userspace, we just install armv7l binaries. @satmandu wrote the armv7l on aarch64 support, though, so they might know what the correct solution is.
> > > 
> > > 
> > > No, we only support armv7l userspace.  The architecture can still be aarch64, however.
> > 
> > We do experimentally support aarch64 userspace, since a stub armv7l userspace is also installed therein...
> 
> No, if we supported aarch64 userspace then we would provide aarch64 binaries.  As soon as ChromeOS supports it then Chromebrew can support it.

> We don't support aarch64 userspace.

We _do unofficially support_ installs on aarch64 userspace machines, since they include an armv7l userspace stub and GLIBC...

**Review by satmandu — APPROVED** [review]
This should at least get around this error...

**Pull request merged**
