### PR TITLE
ruby => 3.3.4

### PR DESCRIPTION
**Pull request by satmandu**
Works properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l` 

### Run the following to get this pull request's changes locally for testing.
```bash
CREW_REPO=https://github.com/satmandu/chromebrew.git CREW_BRANCH=ruby crew update
```

### CODE REVIEW

**Comment by Zopolis4** [comment]
Update the ruby version in `.github/workflows/Repology.yml`?

**Comment by Zopolis4** [comment]
And update the `TargetRubyVersion` in `.rubocop.yml`?

**Comment by Zopolis4** [comment]
Actually, I don't think we need to update the `TargetRubyVersion` for minor releases, my bad.

**Comment by satmandu** [comment]
> Update the ruby version in `.github/workflows/Repology.yml`?

Done.

**Review by Zopolis4 — APPROVED** [review]

**Review by Zopolis4 — APPROVED** [review]

**Pull request merged**
