### PR TITLE
crew_profile_base => 0.0.5

### PR DESCRIPTION
**Pull request by supechicken**
Tested on `x86_64`

### CODE REVIEW

**Comment by satmandu** [comment]
What's the reason for this change?

**Comment by supechicken** [comment]
> What's the reason for this change?

Since we are not using the `master` branch in this recipe, the git tag here needs to be bumped after each pr in `crew-profile-base` repo

**Comment by satmandu** [comment]
But why is `system 'sed', '-i', 's,${TMPDIR},${TMPDIR:-/usr/local/tmp},g', './src/env.d/00-path'` removed?

**Comment by supechicken** [comment]
> But why is `system 'sed', '-i', 's,${TMPDIR},${TMPDIR:-/usr/local/tmp},g', './src/env.d/00-path'` removed?

I committed the fix directly after https://github.com/chromebrew/crew-profile-base/pull/9 merged (https://github.com/chromebrew/crew-profile-base/commit/c68720df6d84b8e45c159f51de3699fdcf372fd5)

**Review by uberhacker — APPROVED** [review]
I like when patches are removed.

**Pull request merged**
