### PR TITLE
rust => 1.71.0

### PR DESCRIPTION
**Pull request by satmandu**
Works properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l` 

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=rust171 CREW_TESTING=1 crew update
```

### CODE REVIEW

**Review by uberhacker — COMMENTED** [review]
What happened to cargo?

**Comment by satmandu** [comment]
> What happened to cargo?

Cargo is there. The bash completions are no longer included.

**Comment by uberhacker** [comment]
> > What happened to cargo?
> 
> Cargo is there. The bash completions are no longer included.

That was my question.  Why were the bash completions removed?

**Comment by satmandu** [comment]
They no longer come with rust.

**Review by uberhacker — APPROVED** [review]

**Pull request merged**
