### PR TITLE
ffmpeg -> 5.1, avisynth -> 3.7.2, tesseract -> 5.2.0

### PR DESCRIPTION
**Pull request by satmandu**
- ffmpeg update + dep updates to fix broken tesseract dependency

Works properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l`

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=ffmpeg CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by saltedcoffii** [comment]
tesseract.rb line 49 why is make run twice

**Comment by satmandu** [comment]
> tesseract.rb line 49 why is make run twice

Got a crash with building on x86_64 which resolved with a second make...

**Comment by saltedcoffii** [comment]
do we know what that crash was and what caused it? I'm finding that a lot of crashes are just from lack of memory or something.

**Review by uberhacker — APPROVED** [review]

**Comment by satmandu** [comment]
> do we know what that crash was and what caused it? I'm finding that a lot of crashes are just from lack of memory or something.

Could be a lack of memory. I was building a Linux kernel at the same time...

**Pull request merged**
