### PR TITLE
crew: Call `pip` when dealing with `py3_*` packages

### PR DESCRIPTION
**Pull request by supechicken**
Inspired from @Zopolis4 

This PR integrates `pip` into `crew` by wrapping up functions with `pkgName =~ /^py3_/` so that we don't need to care about those `py3_` packages anymore :)

### Features
- [x] Fetch package information from pypi
- [x] Get installed package list from `pip`
- [x] Redirect install/uninstall action to `pip`
- [x] Use current `py3_*.rb` implementation if available
- [ ] Check if the given package exists

### Works
- `crew install py3_meson`
```
$ crew install py3_meson
py3_meson: Meson is a cross-platform build system designed to be both as fast and as user friendly as possible. It supports many languages and compilers, including GCC, Clang, PGI, Intel, and Visual Studio. Its build definitions are written in a simple non-Turing complete DSL.
https://mesonbuild.com
Version: 0.64.1
License: Apache License, Version 2.0
Performing pre-flight checks...
Using 'pip' to install Python 3 packages...
Package py3_meson already installed, skipping...
Py3_meson installed!
```
- `crew uninstall py3_meson`
```
$ crew remove py3_meson
Using 'pip' to remove Python 3 packages...
Found existing installation: meson 0.64.1
Uninstalling meson-0.64.1:
  Successfully uninstalled meson-0.64.1
Py3_meson removed!
```

### Untested
- `depends_on 'py3_<pip package>'`

### Todo
- Add comment

### CODE REVIEW

**Comment by satmandu** [comment]
Could this be done with exceptions for some packages which we could handle as pre-built packages?

For instance, py3_numpy takes ages to build.

**Comment by Zopolis4** [comment]
Does pip not distribute pre-built binaries?

**Comment by satmandu** [comment]
@supechicken Anything else needed for this?

**Comment by satmandu** [comment]
It would be nice to be able to get the pip database package versions to show up when you do a crew update, so we don't have to keep updating the py3_ package versions...

**Comment by satmandu** [comment]
Rubocop is whining about `bin/crew:176:7: C: [Correctable] Layout/AssignmentIndentation: Indent the first line of the right-hand-side of a multi-line assignment.`

**Comment by satmandu** [comment]
Even doing something like this during `crew update` might be nice if we can figure out how to make it quicker (or once a day?) 

```
puts 'Updating pip packages...'.lightblue
    @piplist = `pip list | cut -d' ' -f1`.split
    @piplist.drop(2).each do |pip_pkg|
      system "pip install #{pip_pkg} -U", exception: false
    end
``` 
(From the python3 postinstall...)

**Comment by supechicken** [comment]
> @supechicken Anything else needed for this?

The last missing piece is integrating `pip` with `crew whatprovides` (any idea on how to do this😅) and `crew update/upgrade`, but I am afraid that it might slow down everything (python is slow like ruby, surprisingly)...

**Comment by satmandu** [comment]
`pip show` will give you a file list. We could integrate that by creating a pip wrapper which generates the filelist file? Perhaps on a crew install and also a crew update, where crew could check for missing file lists?

**Comment by satmandu** [comment]
maybe modifying to add a filelist is a bad idea... that way the pip remove functionality would get broken.

We should just leave file lists for stub installers (pip package, ruby gem, etc) to those package managers themselves to save ourselves a headache.

**Comment by Zopolis4** [comment]
Yeah. Preferably, we wouldnt have ~150 stub files, and would just make some sort of list file for each supplier (pip, ruby, etc). That would require some modifications to crew, but it'd be worth it.

**Comment by Zopolis4** [comment]
We should also have some way of noticing if the user uses pip manually and modifies packages.

**Comment by supechicken** [comment]
`crew` will not generate any `filelist` since `is_fake` will be set on all `py3` stub packages:
https://github.com/chromebrew/chromebrew/blob/7e66eba2e3f53d1a11b88584559ce01299e8c02b/bin/crew#L205-L214

**Comment by supechicken** [comment]
Okay finally...

`crew update`:
```
$ CREW_TESTING_REPO=https://github.com/supechicken/chromebrew.git CREW_TESTING_BRANCH=pip CREW_TESTING=1 crew update
Updating crew from testing repository...
From https://github.com/supechicken/chromebrew
 * branch              pip        -> FETCH_HEAD
HEAD is now at 1125ac09 Finishing touches
Package lists, crew, and library updated.
Checking for package updates...
buildessential could be updated from 0.1 to 1.23

Checking for Python package updates...
py3_meson could be updated from 0.59.4 to 1.0.0

Run `crew upgrade` to update all packages or `crew upgrade <package1> [<package2> ...]` to update specific packages.
```

`crew upgrade`:
```
$ crew upgrade
Updating packages...
py3_meson: Meson is a cross-platform build system designed to be both as fast and as user friendly as possible. It supports many languages and compilers, including GCC, Clang, PGI, Intel, and Visual Studio. Its build definitions are written in a simple non-Turing complete DSL.

Performing pre-flight checks...
Using 'pip' to install Python 3 packages...
Found existing installation: meson 0.59.4
Uninstalling meson-0.59.4:
  Successfully uninstalled meson-0.59.4
Collecting meson
  Using cached meson-1.0.0-py3-none-any.whl (900 kB)
Installing collected packages: meson
Successfully installed meson-1.0.0
Py3_meson installed!
Packages have been updated.
```

`crew files`:
```
$ crew files py3_meson
py3_meson: Meson is a cross-platform build system designed to be both as fast and as user friendly as possible. It supports many languages and compilers, including GCC, Clang, PGI, Intel, and Visual Studio. Its build definitions are written in a simple non-Turing complete DSL.

/usr/local/lib/python3.11/site-packages
/usr/local/bin/meson
/usr/local/share/man/man1/meson.1
/usr/local/share/polkit-1/actions/com.mesonbuild.install.policy
/usr/local/lib/python3.11/site-packages/meson-0.59.4.dist-info/COPYING
...snip...
Total found: 416
Disk usage: 7.04 MB
```

**Comment by satmandu** [comment]
Hopefully crew remove will know to use pip to uninstall, and not just remove all the files?

**Comment by satmandu** [comment]
Should we also convert the perl modules to use `cpanm` for installs?

(Maybe worth doing before we update `perl` to 5.36.0?)

**Comment by Zopolis4** [comment]
We should always offload the work if possible, if someone else has done it why should we need to duplicate their work? This just applies to language package managers ofc, i.e. pip, gem, shard, etc.

**Comment by supechicken** [comment]
Oops, I think I screw up the whole thing while rebasing with upstream...

**Comment by Zopolis4** [comment]
I know how you feel :p

You can always force push back to the branch and reopen the pr once you fix it, though.

**Comment by Zopolis4** [comment]
Note that due to the way github stores commits, 1125ac096a3851079ab1aa6e9a30c6faf69027d8 is still around, including the branch history before that. You should just be able to just grab this commit in a number of ways.

Easiest one would probably be to go to https://github.com/supechicken/chromebrew/tree/1125ac096a3851079ab1aa6e9a30c6faf69027d8, and then use github's web ui to create a branch from that commit, then fetch that locally.

image

**Comment by satmandu** [comment]
I would still like to see this happen...

**Comment by satmandu** [comment]
@supechicken Do you ever want to fix this and bring it back?

I've got a poor man's version of this for some stuff right now... see my changes in https://github.com/chromebrew/chromebrew/pull/7523

**Comment by supechicken** [comment]
I am currently working on the rewrite of `crew-launcher`, I might try looking into this again when I completed it :)

**Pull request closed without merging**
