### PR TITLE
Update mimalloc, wayland-info, libgnome-games-support, gnome-nibbles

### PR DESCRIPTION
**Pull request by Zopolis4**
- Update mimalloc to 1.8.2
- Update wayland-info to 1.2.0
- Update libgnome-games-support to 1.8.2
- Update gnome-nibbles to 3.8.3

### Run the following to get this pull request's changes locally for testing.
```
CREW_REPO=https://github.com/Zopolis4/chromebrew.git CREW_BRANCH=laver9 crew update
```

### CODE REVIEW

**Review by uberhacker — DISMISSED** [review]
Rubocop doesn't like double quotes when single quotes will work.

**Comment by satmandu** [comment]
I should really submit a PR to make crew run `rubocop -c .rubucop.yml -A packages/package.rb` after builds...

**Comment by Zopolis4** [comment]
I think something like that would be better suited as a post-commit hook.

**Comment by satmandu** [comment]
> I think something like that would be better suited as a post-commit hook...

Ooh. Do you want to implement that?

**Review by satmandu — APPROVED** [review]
👍🏼

**Pull request merged**
