### PR TITLE
Enable WoW64

### PR DESCRIPTION
**Pull request by rafi16jan**

### CODE REVIEW

**Comment by satmandu** [comment]
Does this work?

**Comment by rafi16jan** [comment]
> Does this work?

image

Running winecfg with WINEPREFIX=/usr/local/wine worked... Now I'll try to run some 32 bit exes...

**Comment by rafi16jan** [comment]
> > Does this work?
> 
> image
> 
> Running winecfg with WINEPREFIX=/usr/local/wine worked... Now I'll try to run some 32 bit exes...

Turns out build directly from source on crosh/chromebrew won't work... Compiling with --enable-archs need mingw (or any other c compiler that can cross compile to i386-windows as a target)

**Comment by rafi16jan** [comment]
But turns out clang supports cross compiling to i386-windows. Right now the compilation is under go... need an hour or 2 to see the result

**Comment by rafi16jan** [comment]
And llvm must be added as dependency if this compilation worked

**Comment by rafi16jan** [comment]
The resulting binaries all emits this error:

`ELF: could not open`

I am too unexperienced in this field and couldn't find any reference in the net... Maybe this is something of mismatched architecture or something?

**Comment by Zopolis4** [comment]
https://gitlab.winehq.org/wine/wine/-/releases/wine-9.0#wow64

```
This means that it is possible to run 32-bit Windows applications on a purely 64-bit Unix installation.
```

This should work...

**Comment by Zopolis4** [comment]
[Arch's package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wine-wow64) for this doesn't pass `--enable-win64`, maybe that is causing an issue?

**Comment by Zopolis4** [comment]
I was able to build succesfully with this package file:
```ruby
require 'package'

class Wine < Package
  description 'Wine (originally an acronym for "Wine Is Not an Emulator") is a compatibility layer capable of running Microsoft Windows applications.'
  homepage 'https://www.winehq.org/'
  version '9.0'
  license 'LGPL-2.1'
  compatibility 'x86_64'
  source_url 'https://dl.winehq.org/wine/source/9.0/wine-9.0.tar.xz'
  source_sha256 '7cfd090a5395f5b76d95bb5defac8a312c8de4c070c1163b8b58da38330ca6ee'
  binary_compression 'tar.zst'

  binary_sha256({
     x86_64: '1ea5bc2c10eb8e696feac04e6f238470831743a5d744bf7a5ca53152a4f1fcfc'
  })

  depends_on 'alsa_lib' # R
  depends_on 'desktop_file_utils' => :build
  depends_on 'eudev' # R
  depends_on 'fontconfig' => :build
  depends_on 'giflib' => :build
  depends_on 'glibc' # R
  depends_on 'glib' # R
  depends_on 'gstreamer' # R
  depends_on 'lcms' => :build
  depends_on 'libfaudio' => :build
  depends_on 'libglu' => :build
  depends_on 'libgphoto' # R
  depends_on 'libjpeg' => :build
  depends_on 'libpcap' # R
  depends_on 'libpng' => :build
  depends_on 'libsm' => :build
  depends_on 'libunwind' # R
  depends_on 'libusb' # R
  depends_on 'libx11' # R
  depends_on 'libxcursor' => :build
  depends_on 'libxdamage' => :build
  depends_on 'libxext' # R
  depends_on 'libxi' => :build
  depends_on 'libxkbcommon' # R
  depends_on 'libxrandr' => :build
  depends_on 'llvm'
  depends_on 'mesa' => :build
  depends_on 'mpg123' => :build
  depends_on 'openal' => :build
  depends_on 'opencl_headers' => :build
  depends_on 'opencl_icd_loader' # R
  depends_on 'openldap' => :build
  depends_on 'pulseaudio' # R
  depends_on 'sommelier' # L
  depends_on 'vkd3d' => :build
  depends_on 'wayland' # R
  depends_on 'xdg_base' => :build

  no_lto
  print_source_bashrc

  def self.build
    FileUtils.mkdir_p 'wine64-build'
    Dir.chdir 'wine64-build' do
      unless File.file?('Makefile')
        system "../configure #{CREW_OPTIONS} \
          --disable-maintainer-mode \
          --with-gstreamer \
          --enable-archs=i386,x86_64 \
          --with-x"
      end
      system 'make || make'
      File.write 'wine_config_env', <<~WINE_CONFIG_EOF
        # Wine configuration
        WINEPREFIX="${XDG_CONFIG_HOME}"/.wine
      WINE_CONFIG_EOF
    end
  end

  def self.check
    # There are all sorts of fixme errors, but wine does successfully
    # prompt for install of the wine-mono package, which it then claims
    # to install during the test process...
    Dir.chdir 'wine64-build' do
      system 'make test || true'
    end
  end

  def self.install
    FileUtils.mkdir_p "#{CREW_DEST_PREFIX}/bin"
    Dir.chdir "#{CREW_DEST_PREFIX}/bin" do
      FileUtils.ln_s 'wine64', 'wine'
    end
    Dir.chdir 'wine64-build' do
      system 'make', "DESTDIR=#{CREW_DEST_DIR}", "DLLDIR=#{CREW_DEST_WINE_PREFIX}", 'install'
      FileUtils.install 'wine_config_env', "#{CREW_DEST_PREFIX}/etc/env.d/wine", mode: 0o644
    end
  end

  def self.postinstall
    ExitMessage.add 'To run an application with wine, type `wine path/to/myexecutable.exe` or `wine path/to/myinstaller.msi`.'.lightblue
  end

  def self.remove
    @xdg_config_home = ENV.fetch('XDG_CONFIG_HOME', nil)
    @xdg_config_home = "#{CREW_PREFIX}/.config" if @xdg_config_home.to_s.empty?
    config_dirs = ["#{HOME}/.wine", "#{@xdg_config_home}/.wine"]
    config_dirs.each do |config_dir|
      next unless Dir.exist? config_dir

      print "\nWould you like to remove #{config_dir}? [y/N] "
      case $stdin.gets.chomp.downcase
      when 'y', 'yes'
        FileUtils.rm_rf config_dir
        puts "#{config_dir} removed.".lightgreen
      else
        puts "#{config_dir} saved.".lightblue
      end
    end
  end
end
```

And running it gets these results:
image

It looks like the 64-bit suppor.t works fine, and the 32-bit support is broken, but is still using the new wow64 stuff.

**Comment by Zopolis4** [comment]
Looks like the experimental wow64 support is still quite experimental: https://forums.freebsd.org/threads/wine-9-0r3-experimental-wow64.92594/

Even still, its better than nothing, which is what we had previously.

**Comment by rafi16jan** [comment]
> I was able to build succesfully with this package file:
> 
> ```ruby
> require 'package'
> 
> class Wine < Package
>   description 'Wine (originally an acronym for "Wine Is Not an Emulator") is a compatibility layer capable of running Microsoft Windows applications.'
>   homepage 'https://www.winehq.org/'
>   version '9.0'
>   license 'LGPL-2.1'
>   compatibility 'x86_64'
>   source_url 'https://dl.winehq.org/wine/source/9.0/wine-9.0.tar.xz'
>   source_sha256 '7cfd090a5395f5b76d95bb5defac8a312c8de4c070c1163b8b58da38330ca6ee'
>   binary_compression 'tar.zst'
> 
>   binary_sha256({
>      x86_64: '1ea5bc2c10eb8e696feac04e6f238470831743a5d744bf7a5ca53152a4f1fcfc'
>   })
> 
>   depends_on 'alsa_lib' # R
>   depends_on 'desktop_file_utils' => :build
>   depends_on 'eudev' # R
>   depends_on 'fontconfig' => :build
>   depends_on 'giflib' => :build
>   depends_on 'glibc' # R
>   depends_on 'glib' # R
>   depends_on 'gstreamer' # R
>   depends_on 'lcms' => :build
>   depends_on 'libfaudio' => :build
>   depends_on 'libglu' => :build
>   depends_on 'libgphoto' # R
>   depends_on 'libjpeg' => :build
>   depends_on 'libpcap' # R
>   depends_on 'libpng' => :build
>   depends_on 'libsm' => :build
>   depends_on 'libunwind' # R
>   depends_on 'libusb' # R
>   depends_on 'libx11' # R
>   depends_on 'libxcursor' => :build
>   depends_on 'libxdamage' => :build
>   depends_on 'libxext' # R
>   depends_on 'libxi' => :build
>   depends_on 'libxkbcommon' # R
>   depends_on 'libxrandr' => :build
>   depends_on 'llvm'
>   depends_on 'mesa' => :build
>   depends_on 'mpg123' => :build
>   depends_on 'openal' => :build
>   depends_on 'opencl_headers' => :build
>   depends_on 'opencl_icd_loader' # R
>   depends_on 'openldap' => :build
>   depends_on 'pulseaudio' # R
>   depends_on 'sommelier' # L
>   depends_on 'vkd3d' => :build
>   depends_on 'wayland' # R
>   depends_on 'xdg_base' => :build
> 
>   no_lto
>   print_source_bashrc
> 
>   def self.build
>     FileUtils.mkdir_p 'wine64-build'
>     Dir.chdir 'wine64-build' do
>       unless File.file?('Makefile')
>         system "../configure #{CREW_OPTIONS} \
>           --disable-maintainer-mode \
>           --with-gstreamer \
>           --enable-archs=i386,x86_64 \
>           --with-x"
>       end
>       system 'make || make'
>       File.write 'wine_config_env', <<~WINE_CONFIG_EOF
>         # Wine configuration
>         WINEPREFIX="${XDG_CONFIG_HOME}"/.wine
>       WINE_CONFIG_EOF
>     end
>   end
> 
>   def self.check
>     # There are all sorts of fixme errors, but wine does successfully
>     # prompt for install of the wine-mono package, which it then claims
>     # to install during the test process...
>     Dir.chdir 'wine64-build' do
>       system 'make test || true'
>     end
>   end
> 
>   def self.install
>     FileUtils.mkdir_p "#{CREW_DEST_PREFIX}/bin"
>     Dir.chdir "#{CREW_DEST_PREFIX}/bin" do
>       FileUtils.ln_s 'wine64', 'wine'
>     end
>     Dir.chdir 'wine64-build' do
>       system 'make', "DESTDIR=#{CREW_DEST_DIR}", "DLLDIR=#{CREW_DEST_WINE_PREFIX}", 'install'
>       FileUtils.install 'wine_config_env', "#{CREW_DEST_PREFIX}/etc/env.d/wine", mode: 0o644
>     end
>   end
> 
>   def self.postinstall
>     ExitMessage.add 'To run an application with wine, type `wine path/to/myexecutable.exe` or `wine path/to/myinstaller.msi`.'.lightblue
>   end
> 
>   def self.remove
>     @xdg_config_home = ENV.fetch('XDG_CONFIG_HOME', nil)
>     @xdg_config_home = "#{CREW_PREFIX}/.config" if @xdg_config_home.to_s.empty?
>     config_dirs = ["#{HOME}/.wine", "#{@xdg_config_home}/.wine"]
>     config_dirs.each do |config_dir|
>       next unless Dir.exist? config_dir
> 
>       print "\nWould you like to remove #{config_dir}? [y/N] "
>       case $stdin.gets.chomp.downcase
>       when 'y', 'yes'
>         FileUtils.rm_rf config_dir
>         puts "#{config_dir} removed.".lightgreen
>       else
>         puts "#{config_dir} saved.".lightblue
>       end
>     end
>   end
> end
> ```
> 
> And running it gets these results: image
> 
> It looks like the 64-bit suppor.t works fine, and the 32-bit support is broken, but is still using the new wow64 stuff.

No this is not building from source (that's what I figured after doing it myself). Try to comment the binary_sha256 line and reinstall the wine package (you will notice it should take much longer time when building from source)

**Comment by rafi16jan** [comment]
Don't forget to install llvm

**Comment by Zopolis4** [comment]
Sorry for the confusion-- that is the package file I used to build wine from source.
I added `--enable-archs=i386,x86_64` and removed `--enable-win64`, and added `depends_on 'llvm'`.

[Here's the resulting binary](https://file.io/lIanQlhyrHRh), with a hash of `a3572ae031716f1a4ff125546a84ba431686e0a77fb878be786d96e8d8587361`

**Comment by rafi16jan** [comment]
> Sorry for the confusion-- that is the package file I used to build wine from source. I added `--enable-archs=i386,x86_64` and removed `--enable-win64`, and added `depends_on 'llvm'`.
> 
> [Here's the resulting binary](https://file.io/lIanQlhyrHRh), with a hash of `a3572ae031716f1a4ff125546a84ba431686e0a77fb878be786d96e8d8587361`

Ooh I see

**Comment by satmandu** [comment]
@Zopolis4 why not just add a PR with your binary.

**Comment by Zopolis4** [comment]
Upon rebuilding, I get the ELF issue, so I'm looking into that before I submit a PR.

**Comment by rafi16jan** [comment]
> Upon rebuilding, I get the ELF issue, so I'm looking into that before I submit a PR.

Hahaha... Okay no need to remove the --enable-win64 line and try it myself... Can you update us if you found a solution

**Comment by rafi16jan** [comment]
@Zopolis4 any update?

**Comment by Zopolis4** [comment]
Working on it, no luck so far.

**Comment by Zopolis4** [comment]
It's looking like it might have something to do with this: https://bugs.winehq.org/show_bug.cgi?id=56665

**Comment by rafi16jan** [comment]
> Just reverting abe79e3b52db97cd955574de4c10b22435b2c22f is enough for us to continue building PE modules.

@Zopolis4 will this work?

**Comment by rafi16jan** [comment]
I just realized it is an old commit of Wine 8.12 and that's a downgrade...

**Comment by Zopolis4** [comment]
Looked into this further, it seems this section of `CREW_OPTIONS` is causing issues: `--build=x86_64-cros-linux-gnu --host=x86_64-cros-linux-gnu --target=x86_64-cros-linux-gnu`. 

When I build without that, I don't get the elf issue. I presume the call for cross-compilation is confusing wine.
image

I'll see if there's a way to remove that altogether rather than adding hacky code just for wine.

**Comment by rafi16jan** [comment]
> Looked into this further, it seems this section of `CREW_OPTIONS` is causing issues: `--build=x86_64-cros-linux-gnu --host=x86_64-cros-linux-gnu --target=x86_64-cros-linux-gnu`.
> 
> When I build without that, I don't get the elf issue. I presume the call for cross-compilation is confusing wine. image
> 
> I'll see if there's a way to remove that altogether rather than adding hacky code just for wine.

What if we strip those flags from the CREW_OPTIONS?

**Comment by Zopolis4** [comment]
That's what I'm working on-- I've got a couple outstanding PRs that modify similar areas of `lib/const.rb`, so I'm waiting until those are merged to avoid conflicting work.

**Comment by rafi16jan** [comment]
> That's what I'm working on-- I've got a couple outstanding PRs that modify similar areas of `lib/const.rb`, so I'm waiting until those are merged to avoid conflicting work.

Ohh.. What's the PR number?

**Comment by Zopolis4** [comment]
#10146.

**Pull request closed without merging**
