### PR TITLE
Lint tree with rubocop, again.

### PR DESCRIPTION
**Pull request by Zopolis4**
While attempting to locally run rubocop, I encountered all of these errors. They seemed to mostly be of the Style/RedundantStringEscape style, so I presume its just a new rubocop cop.

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/Zopolis4/chromebrew.git CREW_TESTING_BRANCH=nodiff CREW_TESTING=1 crew update
```

### CODE REVIEW

**Review by satmandu — APPROVED** [review]

**Comment by uberhacker** [comment]
Please don't merge this PR.  We CANNOT make changes like this.  The `system "sed ...` lines need to have the `\` escape characters so the variables are not evaluated.  Otherwise, the lines need to change to `system 'sed ...`.  Single quote `'` instead of double quote `"`.

**Comment by uberhacker** [comment]
These changes are not correct.  Please review and test before creating a PR.

**Comment by satmandu** [comment]
> Please don't merge this PR. We CANNOT make changes like this. The `system "sed ...` lines need to have the `\` escape characters so the variables are not evaluated. Otherwise, the lines need to change to `system 'sed ...`. Single quote `'` instead of double quote `"`.

Are we sure that these are breaking changes, and not something that ruby automagically ignores?

**Comment by Zopolis4** [comment]
If they are breaking, this should be reported to rubocop. I can't easily test this without installing all of the packages, which is not quick to do, and something that I prefer to avoid for a simple lint check.

**Pull request closed without merging**
