### PR TITLE
crew: Add glob support to FileUtils

### PR DESCRIPTION
**Pull request by supechicken**
This PR adds glob support to FileUtils methods with multiple argument support, which means we can use globbing on `FileUtils` without the need of `Dir[]` (just like regular `FileUtils` call) and thus improve the consistency of code

Tested on `x86_64`

### Example
```ruby
# before
FileUtils.rm_rf Dir['*']
FileUtils.cp_r Dir.glob("#{HOME}/*"), '/'

# after
FileUtils.rm_rf '*'
FileUtils.cp_r '~/*', '/'
```

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/supechicken/chromebrew.git CREW_TESTING_BRANCH=fileutils_extended CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by satmandu** [comment]
Shouldn't this be submitted upstream to the ruby fileutils repo?

Otherwise we're maintaining a patch against upstream, which is a maintenance hassle for us.

(It's not terribly hard to submit a PR upstream to fileutils... I did it this year!)

**Comment by supechicken** [comment]
I don't think there would be a chance of merging this to ruby upstream as they need to ensure that all changes need to be backward-compatible (this change will break with files that have symbols like `~` or `*` in the filename, although this was very rare)

But anyway we can give a try on it :)

**Comment by uberhacker** [comment]
Can we convert this to draft and fix the conflicting file?

**Comment by uberhacker** [comment]
Any upstream updates on this?

**Comment by satmandu** [comment]
Please submit this to upstream! Otherwise we will be maintaining a downstream patch to FileUtils indefinitely!

(Upstream DOES accept patches! I've done it!)

**Comment by Zopolis4** [comment]
> I don't think there would be a chance of merging this to ruby upstream as they need to ensure that all changes need to be backward-compatible.

They will merge backwards-incompatible changes-- here is the [list of compatibility issues in Ruby 3.4](https://docs.ruby-lang.org/en/master/NEWS_md.html#label-Compatibility+issues).

image

We probably wont be able to get this change into Ruby 3.4, but the earlier we submit it upstream the sooner we'll be able to use it.

**Pull request closed without merging**
