### PR TITLE
lib/package: Get rid of `eval` strings 

### PR DESCRIPTION
**Pull request by supechicken**
## Changes
- Change all `class_eval <<~EOF` calls into `define_singleton_method()` with native ruby blocks
- The `print_boolean_properties()` logic is now handled in `def boolean_property`

### Run the following to get this pull request's changes locally for testing.
```bash
CREW_REPO=https://github.com/supechicken/chromebrew.git CREW_BRANCH=package_rb_cleanup crew update
```

### CODE REVIEW

**Comment by satmandu** [comment]
Robocop lint failure...

**Comment by supechicken** [comment]
Rubocop hates camelCase...

**Comment by uberhacker** [comment]
> Rubocop hates camelCase...

Good because I hate it too. :grinning:

**Review by uberhacker — DISMISSED** [review]
Not sure I completely understand the abstracted logic here but if the tests pass...

**Review by uberhacker — COMMENTED** [review]
Bump crew version in `const.rb`?

**Comment by supechicken** [comment]
> Bump crew version in `const.rb`?

Done

**Review by uberhacker — APPROVED** [review]

**Pull request merged**
