### PR TITLE
epiphany => 43.1

### PR DESCRIPTION
**Pull request by supechicken**
I need to figure out this error first... (installing `libiconv` does not help)
```
Run-time dependency libarchive found: NO (tried cmake)

meson.build:96:0: ERROR: Dependency lookup for libarchive with method 'pkgconfig' failed: Could not generate cargs for libarchive:
Package iconv was not found in the pkg-config search path.
Perhaps you should add the directory containing `iconv.pc'
to the PKG_CONFIG_PATH environment variable
Package 'iconv', required by 'libarchive', not found
```

### CODE REVIEW

**Comment by satmandu** [comment]
iconv is part of glibc... are you building with an older glibc?

**Comment by satmandu** [comment]
useful to check the meson build logs. looking at /usr/local/tmp/crew/epiphany.20230227220330.dir/builddir/meson-log/meson-log.txt...

```
Determining dependency 'libarchive' with pkg-config executable '/usr/local/bin/pkg-config'
env[PKG_CONFIG_PATH]:
Called `/usr/local/bin/pkg-config --modversion libarchive` -> 0
3.6.2
env[PKG_CONFIG_PATH]:
Called `/usr/local/bin/pkg-config --cflags libarchive` -> 1
```
Now let's try that command:
```
chronos@cheekon-x86_64 /usr/local/tmp/crew/epiphany.20230227220330.dir/builddir/meson-logs $ /usr/local/bin/pkg-config --cflags libarchive
Package iconv was not found in the pkg-config search path.
Perhaps you should add the directory containing `iconv.pc'
to the PKG_CONFIG_PATH environment variable
Package 'iconv', required by 'libarchive', not found
```
hmmm...

**Comment by satmandu** [comment]
Arch is building libarchive with these flags: 
```
--without-xml2 \
      --without-nettle \
      --disable-static
```
NOTE ALSO that arch does this:
```
  sed -i "s/iconv //" "$pkgdir"/usr/lib/pkgconfig/libarchive.pc
```
Maybe we should at least be doing at least that last bit?

See https://github.com/archlinux/svntogit-packages/blob/packages/libarchive/trunk/PKGBUILD

Can you build libarchive with that locally and see if that fixes the issue?

**Review by satmandu — APPROVED** [review]

**Comment by satmandu** [comment]
44.beta requires webkitgtk 2.40, so that's not an option at the moment...

**Review by uberhacker — APPROVED** [review]

**Pull request merged**
