### PR TITLE
git -> 2.37.1, disable optimization and binary stripping

### PR DESCRIPTION
**Pull request by satmandu**
- This is built with debugging enabled and with stripping disabled, to help track down the [issues on AMD](https://github.com/chromebrew/chromebrew/issues?q=is%3Aissue+is%3Aopen+label%3AAMD).

Works properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l`

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=git2371 CREW_TESTING=1 crew update
```

### CODE REVIEW

**Comment by saltedcoffii** [comment]
let's not merge this package. instead let's tell people in the AMD issues to run `./install.sh` using this repo instead of the main chromebrew one.

**Comment by satmandu** [comment]
That's an interesting idea...

**Comment by satmandu** [comment]
That would be this, right?
```
curl -OLf https://github.com/chromebrew/chromebrew/raw/master/install.sh
OWNER=satmandu BRANCH=git2371 ./install.sh
```

**Comment by saltedcoffii** [comment]
> That would be this, right?
> ```
> curl -OLf https://github.com/chromebrew/chromebrew/raw/master/install.sh
> chmod +x install.sh
> OWNER=satmandu BRANCH=git2371 ./install.sh
> ```

yes! the environment variables can be passed to bash directly as well during the pipe like we do the `CREW_FORCE_INSTALL` variable.

**Comment by satmandu** [comment]
FYI This still results in segfaults on the and systems...

curiously, many binaries for a grunt M103 recovery image also crash when run in a docker container on an Intel x86_64 system. Does anyone have an AMD system (not necessarily a Chromebook) they can do some testing on?

**Pull request closed without merging**
