### PR TITLE
JSON-GLib 1.8.1-b3774f5 -> 1.9.2

### PR DESCRIPTION
**Pull request by Zopolis4**
### Run the following to get this pull request's changes locally for testing.
```bash
CREW_REPO=https://github.com/Zopolis4/chromebrew.git CREW_BRANCH=overgrill crew update
```

### CODE REVIEW

**Review by uberhacker — APPROVED** [review]
I thought we were excluding docs but I'm fine with including them.

**Comment by Zopolis4** [comment]
Oh, I was just sticking to package defaults whenever possible.

**Comment by satmandu** [comment]
> Oh, I was just sticking to package defaults whenever possible.

Please rebuild this with docs disabled. People can find that stuff on the web...

**Comment by uberhacker** [comment]
> > Oh, I was just sticking to package defaults whenever possible.
> 
> Please rebuild this with docs disabled. People can find that stuff on the web...

I agree with this statement because if we build all packages with docs included, it can add a significant amount of disk usage on already strapped for space Chromebooks with tiny hard drives.  However, it might be nice to include a link to the documentation in a postinstall message.

**Comment by satmandu** [comment]
> > > Oh, I was just sticking to package defaults whenever possible.
> > 
> > Please rebuild this with docs disabled. People can find that stuff on the web...
> 
> I agree with this statement because if we build all packages with docs included, it can add a significant amount of disk usage on already strapped for space Chromebooks with tiny hard drives.  However, it might be nice to include a link to the documentation in a postinstall message.

I think that if you're installing json-glib you know how to find the documentation...

**Comment by Zopolis4** [comment]
Fair enough, especially when it's just html documentation-- manpages are smaller and we compress them, and theres value to having them integrated into the system, but there's no point to keeping a bunch of webpages locally.

**Review by satmandu — APPROVED** [review]

**Pull request merged**
