### PR TITLE
Add quick armv7l support to unit testing CI

### PR DESCRIPTION
**Pull request by Zopolis4**
And I do mean quick-- there a number of improvements to be made to this action, but most of them are waiting on #9707, so lets just get more coverage for now.

### CODE REVIEW

**Comment by Zopolis4** [comment]
quick as in how long it took to implement, not how long it takes to run now... :sweat_smile:

**Comment by uberhacker** [comment]
This is great but shouldn't the priority be to fix the broken arm build process first?  A recent update broke it and I will submit a revert PR if a fix is not implemented soon.

**Comment by Zopolis4** [comment]
working on that as well

**Review by satmandu — APPROVED** [review]

**Comment by satmandu** [comment]
Thank you for putting this together! This should hopefully prevent breakage in the future...

**Pull request merged**
