### PR TITLE
Add php83 package

### PR DESCRIPTION
**Pull request by uberhacker**
Tested on arm and x86_64.

### CODE REVIEW

**Review by satmandu — APPROVED** [review]

**Comment by satmandu** [comment]
Are GitHub actions not working to do the unit tests?

**Comment by uberhacker** [comment]
> Are GitHub actions not working to do the unit tests?

@Zopolis4?

**Comment by uberhacker** [comment]
> It seems like the Handoff workflow never triggered in the first place-- probably a server issue or something, not much I can do about.
> 
> I'm on my phone right now tho, so I only gave it a pretty cursory look.

Looks like the Handoff worked afterall.

**Comment by uberhacker** [comment]
It appears the progress bar has an issue on the github actions server used for unit tests.
```
cmake: CMake is an open-source, cross-platform family of tools designed to build, test and package software.
Performing pre-flight checks...
Precompiled binary available, downloading...
25l    3.96 MB/10.72 MB  
25h#<Thread:0x00007f014c361ba0 /usr/local/lib/crew/lib/progress_bar.rb:82 run> terminated with exception (report_on_exception is true):
/usr/local/lib/crew/lib/progress_bar.rb:97:in `*': negative argument (ArgumentError)

        print (@bar_char * completed_length).send(*@bar_front_color),
                           ^^^^^^^^^^^^^^^^
	from /usr/local/lib/crew/lib/progress_bar.rb:97:in `block in show'
/usr/local/lib/crew/lib/progress_bar.rb:97:in `*': negative argument (ArgumentError)

        print (@bar_char * completed_length).send(*@bar_front_color),
                           ^^^^^^^^^^^^^^^^
	from /usr/local/lib/crew/lib/progress_bar.rb:97:in `block in show'
#=#=#                                                                         

                                                                           0.3%
######################################################                    76.3%
######################################################################## 100.0%
Cmake archive downloaded.
Unpacking archive using 'tar', this may take a while...
Removing since upgrade or reinstall...
Checking for conflicts of cmake with files from installed packages...
```

**Comment by satmandu** [comment]
> It seems like the Handoff workflow never triggered in the first place-- probably a server issue or something, not much I can do about.
> 
> I'm on my phone right now tho, so I only gave it a pretty cursory look.

Looks like it started working.

**Pull request merged**
