### PR TITLE
Filecmd 5.43 => 5.44

### PR DESCRIPTION
**Pull request by uberhacker**
Add lzlib package

Fixes #7788.

### CODE REVIEW

**Comment by satmandu** [comment]
You also need the zstd and GLIBC deps like in my PR...

**Comment by satmandu** [comment]
(run the getrealdeps script to verify...)

**Review by satmandu — COMMENTED** [review]
Also add `no_strip` to filecmd?

**Comment by uberhacker** [comment]
Rather than using `no_strip`, why don't we fix the syntax error?

**Comment by satmandu** [comment]
> Rather than using `no_strip`, why don't we fix the syntax error?

You're right. Just realized I'm getting it on other packages too.

**Review by satmandu — APPROVED** [review]

**Pull request merged**
